var quotes = ["Happiness is not by chance, but by choice",
    "The best way to predict the future is to create it",
    "Smile, and the world smiles with you",
    "Every day may not be good, but there's something good in every day",
    "Happiness is the only thing that multiplies when you share it",
    "Do more of what makes you happy",
    "The sun always shines after the rain",
    "Choose joy, even in the smallest things",
    "Happiness is homemade",
    "Dream big, stay positive, and enjoy the journey",
    "You are capable of amazing things",
    "Find joy in the journey",
    "Radiate positivity, and it will come back to you",
    "Happiness is not a destination; it’s a way of life",
    "Be the reason someone smiles today",
    "Wherever life plants you, bloom with grace",
    "Life is better when you’re laughing",
    "Start each day with a grateful heart",
    "It’s a good day to have a good day",
    "Be happy with what you have while working for what you want",
    "Let your smile change the world, but don’t let the world change your smile",
    "Happiness is the secret to all beauty",
    "Take time to do what makes your soul happy",
    "Positive vibes only",
    "Happiness is contagious, spread it everywhere",
    "Believe in yourself and all that you are",
    "Good vibes, good life",
    "Every moment is a fresh beginning",
    "Count your blessings, not your troubles",
    "Create your own sunshine",
    "The happiest people don’t have the best of everything; they make the best of everything",
    "Joy is the simplest form of gratitude",
    "A positive mindset brings positive things",
    "Happiness blooms from within",
    "Happiness comes in waves. Catch the next one",
    "Do what you love and love what you do",
    "You bring your own sunshine wherever you go",
    "Happiness is a warm heart and an open mind",
    "Keep shining, the world needs your light",
    "Life is too short to be anything but happy",
    "The more you praise and celebrate your life, the more there is in life to celebrate",
    "Your vibe attracts your tribe",
    "Happiness starts with you",
    "Gratitude turns what we have into enough",
    "Collect moments, not things",
    "Keep looking up; that’s the secret of life",
    "Focus on the step in front of you, not the whole staircase",
    "Happiness is a journey, not a destination",
    "Be so happy that when others see you, they feel happy too",
    "There is no path to happiness; happiness is the path",
]

function showQuotes() {
    var randomNumber = Math.floor(Math.random() * quotes.length)
    document.getElementById('quote').innerHTML = quotes[randomNumber]
}
